- name: nginx install and run
  hosts: nginx
  #hosts: all
  become: yes #take sudo access
  serial: 3
  tasks:
  - name: install nginx
    ansible.builtin.package: #heterongenous module that can work for all distros
      name: nginx
      state: present
  
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes